### ISSUE TITLE
More compiler information through community mappings

### ISSUE THREAD

**Issue by brucethemoose** [hpi-swa/native-minecraft-server#1]
Reading this part of the medium blog post:

`The application is closed-source so we can’t just look at the source code to determine all reflective accesses. While decompilation of compiled code is possible, the code has been obfuscated by the development team beforehand, randomizing as much information as possible. Therefore, without having in-depth access to the source code we are not able to determine if every class, method, or field that could be accessed through reflections has actually been caught. `

I remembered that open source mappings of Minecraft's source *do* exist... through 3rd party efforts, like yarn:

https://github.com/FabricMC/yarn

https://maven.fabricmc.net/docs/yarn-1.19.2+build.8/index.html

Would this aid AOT compilation in any way? And would it enable mod support, as long as the mods themselves have unobfuscated jars and/or available source files?

Compilation of the official jar is somewhat impractical without mod support, as very few performance/resource usage conscious server owners run the official Mojang server jar by itself.

**Comment by fniephaus** [comment]
> Would this aid AOT compilation in any way?

While those community-maintained source mappings may be very helpful for mod developers, I'm not sure it would help AOT compilation much to be honest. For compiling the Minecraft server with GraalVM Native Image, the students didn't need access to decompiled code, although that may be useful to ensure that all resources, reflective calls, etc. are covered by the configuration. This, however, can also be verified by exercising the server in different ways, which is what the students have done.

> And would it enable mod support, as long as the mods themselves have unobfuscated jars and/or available source files?

I have no idea how mod loading works but I don’t see a reason why mods shouldn’t work with GraalVM Native Image. You probably need to provide Native Image with appropriate configuration for the mods that you want to use. The [trace agent](https://www.graalvm.org/22.2/reference-manual/native-image/metadata/AutomaticMetadataCollection/) may be able to help you with this, it can even extend existing configuration.

> Compilation of the official jar is somewhat impractical without mod support, as very few performance/resource usage conscious server owners run the official Mojang server jar by itself.

Yes, that makes sense. More work is needed to try out different mods and generate configurations for them. But as already mentioned, I think that should be possible. Please feel free to take a closer look and let us know if you run into any problems!

**Comment by brucethemoose** [comment]
👍
