### ISSUE TITLE
specific versions to maintain interest in the project, must be 1.8 and 1.16

### ISSUE THREAD

**Issue by mckaygerhard** [hpi-swa/native-minecraft-server#2]
currently unless this is a learning project...no one will be interested in supporting it since the most used versions are 1.16 and 1.8...(for survival and pvp respectively)

When the jar is used and tested, you will have more feedback from the users... who are the ones who play... taking into account that it is the purpose, otherwise this remains a pure learning tool or hobby

NOTE: Take note that since 1.16 accounts are forced to be M$ crap so that's another reason why players just dont like, specially community of free software.. as a player i dont use 1.18.. just 1.8 for pvp and 1.16 for survival games, most servers are compatible with such version also.

**Comment by WalshyDev** [comment]
This is objectively not true.

Let's look at some data.
CraftBukkit/Spigot/Paper - https://bstats.org/global/bukkit
1.16.5 - 7.8%
1.8.8 - 6.1%

Meanwhile, 1.19 alone makes up 22.3%. Literally more than 1.16.5 + 1.8.8 combined.

BungeeCord - https://bstats.org/global/bungeecord
1.19 - 60%
1.16 - 5.4%

---

Just because you do not like changes does not mean you speak for the majority. This project is open source, if you wish to use those versions then you can support them yourself. Saying "no one will be interested in supporting it" is frankly rude.
Finally, If you read the README it says
> Disclaimer: This project is meant for demonstration purposes only and intended to help the Minecraft community evaluate the use of GraalVM Native Image. Please use at your own risk.

I can't speak for the author on their intentions here but I just needed to interject reading this issue. This looks like a cool project. You should be respectful to authors of any service/software. Especially free ones.

**Comment by mckaygerhard** [comment]
> This is objectively not true.

do you play minetest seriusly or just another developer? i mean PLAY not just sporadically play

> 
> Let's look at some data. CraftBukkit/Spigot/Paper - https://bstats.org/global/bukkit 1.16.5 - 7.8% 1.8.8 - 6.1%
> 
> Meanwhile, 1.19 alone makes up 22.3%. Literally more than 1.16.5 + 1.8.8 combined.
> 
> BungeeCord - https://bstats.org/global/bungeecord 1.19 - 60% 1.16 - 5.4%
> 
> Just because you do not like changes does not mean you speak for the majority. 

the stats are not from the most players

> 
> > Disclaimer: This project is meant for demonstration purposes only and intended to help the Minecraft community evaluate the use of GraalVM Native Image. Please use at your own risk.
> 
> I can't speak for the author on their intentions here but I just needed to interject 

my comment plays: _"...you will have more feedback from the users... who are the ones who play.."_

**Comment by clrxbl** [comment]
> > This is objectively not true.
> 
> do you play minetest seriusly or just another developer? i mean PLAY not just sporadically play
> 
> > Let's look at some data. CraftBukkit/Spigot/Paper - [bstats.org/global/bukkit](https://bstats.org/global/bukkit) 1.16.5 - 7.8% 1.8.8 - 6.1%
> > Meanwhile, 1.19 alone makes up 22.3%. Literally more than 1.16.5 + 1.8.8 combined.
> > BungeeCord - [bstats.org/global/bungeecord](https://bstats.org/global/bungeecord) 1.19 - 60% 1.16 - 5.4%
> > Just because you do not like changes does not mean you speak for the majority.
> 
> the stats are not from the most players
> 
> > > Disclaimer: This project is meant for demonstration purposes only and intended to help the Minecraft community evaluate the use of GraalVM Native Image. Please use at your own risk.
> > 
> > 
> > I can't speak for the author on their intentions here but I just needed to interject
> 
> my comment plays: _"...you will have more feedback from the users... who are the ones who play.."_

Please provide a source from your statistics that are "from the most players".

**Comment by fniephaus** [comment]
I believe this project should be seen as a starting point: it shows what to do to compile the Minecraft server to native. The students focused on getting things to work and supporting multiple server versions wasn't a goal AFAIK. Having said that, if the community can help provide feedback which versions are most interesting to support, that's great. If someone is interested in contributing support for a particular version, even better!

**Comment by mckaygerhard** [comment]
> if the community can help provide feedback which versions are most interesting to support, that's great. If someone is interested in contributing support for a particular version, even better!

well i guess If the project provides a starting point of how to implement 1.8 and 1.16 the players where we also are some developer (**since clearly the guys above are not a pvp stronger player)** so then most we would provide more feedback, 
 cos other than that it's obvious that no player will be interested. since this job involves stopping playing for more than a day to read and learn

for that we need a started effort, by example i am a player and i have more partner players but neither me or them uses any other versions rather than 1.8 or 1.16

**Comment by splatboydev** [comment]
> well i guess If the project provides a starting point of how to implement 1.8 and 1.16 the players where we also are some developer (**since clearly the guys above are not a pvp stronger player)**...

I find this statement hard to understand.

**Comment by mckaygerhard** [comment]
> > well i guess If the project provides a starting point of how to implement 1.8 and 1.16 the players where we also are some developer (**since clearly the guys above are not a pvp stronger player)**...
> 
> I find this statement hard to understand.

means you dont play well player vs player.. means you and many developers are noobs playing, best stronger players uses 1.8 and 1.16

**Comment by krono** [comment]
This conversation has strayed far of the score of this project, let's keep things focussed.
