### ISSUE TITLE
Using Minecraft for the creation of climate neutral cities

### ISSUE THREAD

**Issue by steckhan** [hpi-swa/native-minecraft-server#3]
Dear HPI-SWA Group,

I would like to talk with you, about an interesting EU Project that would like to use Minecraft for their co-creation processes.
How could I contact you to explain the ideas?

Best
Nico

**Comment by JensLincke** [comment]
Hi,
we can have quick zoom chat if you like, just contact me at jens.lincke@hpi.de 
Best, Jens

**Comment by codespearhead** [comment]
Should this issue be closed?

If so, I'm pretty sure the same goes for #2
