### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by wylited** [hpi-swa/native-minecraft-server#4]
Hi, I was just wondering how difficult it would be if I wanted to update this to 1.19.3 myself for personal use.
i was also wondering if its possible to use datapacks along side it?
thanks in advance.

**Comment by methbkts** [comment]
Maybe changing the value of `SERVER_JAR_DL` in `build.sh` with the `1.19.3` version of the `server.jar` can do the trick.
Didn't test it already but will make feedback as soon as I will.

For the datapacks, maybe after extracting resources from `server.jar` you can add it in the `datapacks` folder, something to try but not sure that it will work.

EDIT: it seems to be a lot more difficult for datapacks

**Comment by wylited** [comment]
Thanks, I will try this.
